# Generated by Django 5.0.6 on 2024-06-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasalapp', '0003_alter_playlist_movie_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
