# Generated by Django 5.0.6 on 2024-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasalapp', '0004_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.URLField()),
            ],
        ),
    ]
