# Generated by Django 5.0.6 on 2024-06-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasalapp', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fasalapp.user'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='poster',
            field=models.URLField(default='default_poster_url_here'),
        ),
    ]
