# Generated by Django 5.0.6 on 2024-06-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasalapp', '0006_playlist_user_alter_playlist_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fasalapp.user'),
        ),
    ]
