# Generated by Django 5.0.6 on 2024-06-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasalapp', '0008_alter_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='poster',
            field=models.URLField(),
        ),
    ]
